apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-mutator
  namespace: default
spec:
  selector:
    matchLabels:
      app: general-mutator
  template:
    metadata:
      labels:
        app: general-mutator
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: general-mutator
          image: mwennrich/general-mutator:latest
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: "/etc/general-mutator/tls/"
            - name: rules
              mountPath: "/etc/general-mutator/rules/"
      volumes:
        - name: tls
          secret:
            secretName: general-mutator-certs
        - name: rules
          configMap:
            name: general-mutator-rules
---
apiVersion: v1
kind: Service
metadata:
  name: general-mutator
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: general-mutator
