apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutator
  namespace: default
spec:
  selector:
    matchLabels:
      app: mutator
  template:
    metadata:
      labels:
        app: mutator
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: mutator
          image: ghcr.io/mwennrich/mutator:latest
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: "/etc/mutator/tls/"
            - name: rules
              mountPath: "/etc/mutator/rules/"
      volumes:
        - name: tls
          secret:
            secretName: mutator-certs
        - name: rules
          configMap:
            name: mutator-rules
---
apiVersion: v1
kind: Service
metadata:
  name: mutator
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: mutator
