apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-mutator
  namespace: default
spec:
  selector:
    matchLabels:
      app: pod-mutator
  template:
    metadata:
      labels:
        app: pod-mutator
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: pod-mutator
          image: ghcr.io/mwennrich/pod-mutator:latest
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: "/etc/pod-mutator/tls/"
            - name: rules
              mountPath: "/etc/pod-mutator/rules/"
      volumes:
        - name: tls
          secret:
            secretName: pod-mutator-certs
        - name: rules
          configMap:
            name: pod-mutator-rules
---
apiVersion: v1
kind: Service
metadata:
  name: pod-mutator
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: pod-mutator
