apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-mutator-rules
  namespace: default
data:
  rules.json: |
    {
      "rules": [
        {
          "namespace": "^(default)$",
          "name": "^(echoserver.*)$",
          "patch": "[{\"op\": \"add\", \"path\": \"/metadata/labels/mwen\", \"value\": \"test\"}]"
        }
      ]
    }
