apiVersion: v1
kind: ConfigMap
metadata:
  name: mutator-rules
  namespace: default
data:
  rules.json: |
    {
      "rules": [
        {
          "namespace": "^(default)$",
          "name": "^(echoserver.*)$",
          "patch": "[{\"op\": \"add\", \"path\": \"/spec/template/metadata/labels/mwen\", \"value\": \"test\"}]"
        },
        {
          "namespace": "^(kube-system)$",
          "name": "^(coredns.*)$",
          "patch": "[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"coredns/coredns:1.10.1\"}]"
        }
      ]
    }
